environment:
  github_app_id: "12345"
  report_status: "true"
  verify_type: "emv"
  oauth_client_secret_path: "/var/openfaas/secrets/ts-client-secret"
  client_secret: ""
  client_id: "7a9cbbf3e0bce602784f"
  oauth_provider_base_url: ""
  oauth_telar_base_url: ""
  oauth_provider: "github"
  base_route: "/auth"
  write_debug: "true"

# FAAS_ENV=openfaas-fn

#######   Set secrets for K8S   ###########

#  kubectl -n openfaas-fn create secret generic secrets --from-file=./key --from-file=./key.pub --from-file=./serviceAccountKey.json \
#   --from-literal="ts-client-secret=$CLIENT_SECRET" --from-literal="mongo-pwd=$MONGO_PWD" \
#   --from-literal="recaptcha-key=$RECAPTCHA_KEY" --from-literal="ref-email-pass=$REF_EMAIL_PASS" \
#   --from-literal="redis-pwd=$REDIS_PWD" --from-literal="admin-username=$ADMIN_USERNAME"\
#   --from-literal="admin-password=$ADMIN_PASSWORD" --from-literal payload-secret="$PAYLOAD_SECRET"\
#   --from-literal="phone-auth-token=$PHONE_AUTH_TOKEN" --from-literal="phone-auth-id=$PHONE_AUTH_ID" 

#######   Set secrets for OFC   ###########
# faas-cli cloud seal --name red-gold-secrets \
# --literal mongo-pwd="$MONGO_PWD" --literal recaptcha-key="$RECAPTCHA_KEY" \
# --from-file="key" --from-file="key.pub" --from-file="serviceAccountKey.json" \
# --literal ts-client-secret="$CLIENT_SECRET" --literal redis-pwd="$REDIS_PWD" \
# --literal admin-username="$ADMIN_USERNAME" \
# --literal admin-password="$ADMIN_PASSWORD" --literal payload-secret="$PAYLOAD_SECRET" \
# --literal ref-email-pass="$REF_EMAIL_PASS" --literal phone-auth-token="$PHONE_AUTH_TOKEN" \
# --literal phone-auth-id="$PHONE_AUTH_ID"