environment:
    gateway: http://gateway.openfaas:8080
    origin: {{.Origin}}
    web_domain: {{.WebDomain}}
    external_domain: {{.ExternalDomain}}
    cookie_root_domain: {{.CookieRootDomain}}
    external_redirect_domain: {{.Scheme}}://{{.Domain}}/auth
    websocket_server_url: {{.WebSocketURL}}